[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "air[sql,standard]>=0.33.1",
    "sqlmodel>=0.0.25",
    "pytest>=8.0.0",
    "pytest-cov>=5.0.0",
]
